# Generated by Django 5.2.7 on 2025-10-16 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Phones", "Phones"),
                            ("Laptops", "Laptops"),
                            ("Consoles", "Consoles"),
                            ("iPads", "iPads"),
                            ("Accessories", "Accessories"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Specification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("brand", models.CharField(max_length=50)),
                ("model_type", models.CharField(max_length=50)),
                ("color", models.CharField(blank=True, max_length=50, null=True)),
                ("internal_storage", models.IntegerField(blank=True, null=True)),
                ("RAM", models.IntegerField(blank=True, null=True)),
                ("card_slot", models.CharField(blank=True, max_length=50, null=True)),
                ("eSim", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Used", "Used"),
                            ("Pre-owned", "Pre-owned"),
                        ],
                        max_length=20,
                    ),
                ),
                ("swap_allowed", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "product_status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Out of stock", "Out of stock"),
                        ],
                        default="Available",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="products/images/"
                    ),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True, null=True, upload_to="products/videos/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="post_api.category",
                    ),
                ),
                (
                    "specification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="post_api.specification",
                    ),
                ),
            ],
        ),
    ]
