# Generated by Django 5.2.7 on 2025-11-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount_percentage",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
