# Generated by Django 5.2.7 on 2025-11-24 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_api", "0002_product_discount_percentage_product_discount_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_category",
            field=models.CharField(
                choices=[
                    ("Phones", "Phones"),
                    ("Laptops", "Laptops"),
                    ("Consoles", "Consoles"),
                    ("iPads", "iPads"),
                    ("Accessories", "Accessories"),
                ]
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
