# Generated by Django 5.2.7 on 2025-11-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("post_api", "0003_alter_product_product_category_delete_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="specification",
        ),
        migrations.AddField(
            model_name="product",
            name="brand",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="card_slot",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="condition",
            field=models.CharField(
                choices=[("New", "New"), ("Used", "Used"), ("Pre-owned", "Pre-owned")],
                default="New",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="eSim",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="internal_storage",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="model_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="ram",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="swap_allowed",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_category",
            field=models.CharField(
                choices=[
                    ("Phones", "Phones"),
                    ("Laptops", "Laptops"),
                    ("Consoles", "Consoles"),
                    ("iPads", "iPads"),
                    ("Accessories", "Accessories"),
                ],
                null=True,
            ),
        ),
    ]
