# Generated by Django 5.2.7 on 2025-12-07 17:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post_api", "0004_remove_product_specification_product_brand_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Specification",
        ),
        migrations.AlterField(
            model_name="product",
            name="image",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="image"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="video",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="video"
            ),
        ),
    ]
